---
   
   - name: "Instalando pacotes do php..." 
     yum: name={{ item }} state=present
     with_items:
         - php
         - php-common
         - php-cli
         - php-mysql
         - php-gd
         - php-xml
         - php-mbstring
         - php-fpm
         - php-ldap
         - php-xmlrpc
