---
   - name: "Instalar serviço mariadb"
     yum: pkg=mariadb-server state=latest
     tags: installmariadb

   - name: "Instalando pacote Mysql-Python"
     yum: pkg=MySQL-python state=latest
     tags: installmysqlpython

   - name: "Inicia serviço mariadb"
     service: name=mariadb state=restarted
     tags: startmariadb
