---
   - name: "Desativando Selinux..."
     selinux: policy=targeted state=permissive
     run_once: true
     tags:
       - basics

#   - name: "Parando serviço do Firewalld..."
#     service: name=firewalld state=stopped enabled=no
#     run_once: true
#     tags: 
#       - basics
#       - stop_firewall

#   - name: "Desativando serviço do Firewalld..." 
#     service: name={{ item }} enabled=no state=stopped
#     with_items:
#       - firewalld
#     tags: basics
