- hosts: localhost
  vars_files:
    - vars.yml

  tasks: 
    - name: AWS | Launch instance
      ec2:
        key_name: "{{ key }}"
        image: "{{ image }}"
        wait: yes
        type: "{{ type }}"
        count: 1
        group_id: "{{ nsg }}"
        vpc_subnet_id: "{{ subnet }}"
        assign_public_ip: yes
        region: "{{ region }}"
        instance_tags:
          Name: "{{ instance_name }}"
        volumes:
        - device_name: /dev/sda1        
          volume_size: 30
          delete_on_termination: true      
      register: machine     
  
    - name: AWS | Service ssh up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        timeout: 600
        state: started
      with_items: "{{ machine.instances }}"
